In [2]:
import glob, matplotlib.pyplot as plt, numpy as np, pandas as pd
%matplotlib inline
%precision 4
plt.style.use('ggplot')

In [3]:
np.set_printoptions(formatter={'float':lambda x: '%.3f' %x})

In [10]:
np.random.seed(123)

In [11]:
#sampling is done with replacement by default
np.random.choice(4,12)

array([2, 1, 2, 2, 0, 2, 2, 1, 3, 2, 3, 1])

In [12]:
#Probability weights can be given
np.random.choice(4,12,p=[.4,.1,.1,.4])

array([3, 3, 1, 0, 0, 3, 1, 0, 0, 3, 0, 0])

In [16]:
x = np.random.randint(0,10,(8,12))
x

array([[6, 4, 4, 7, 0, 0, 9, 8, 8, 4, 8, 6],
       [1, 6, 8, 7, 9, 1, 7, 1, 7, 9, 8, 7],
       [1, 3, 1, 8, 7, 5, 1, 2, 5, 2, 2, 9],
       [3, 2, 6, 7, 9, 1, 3, 8, 3, 7, 9, 9],
       [3, 3, 5, 6, 0, 8, 7, 7, 4, 4, 5, 0],
       [8, 9, 2, 5, 1, 5, 9, 2, 4, 3, 0, 3],
       [7, 7, 2, 5, 1, 7, 5, 9, 1, 2, 8, 5],
       [0, 9, 3, 3, 3, 1, 7, 6, 3, 1, 7, 2]])

In [17]:
#sampling individual elements
np.random.choice(x.ravel(),12)

array([3, 6, 0, 4, 9, 4, 3, 9, 1, 5, 3, 3])