In [3]:
import glob, matplotlib.pyplot as plt, numpy as np, pandas as pd, csv

In [4]:
bristo = np.genfromtxt("Bristol_86.csv",delimiter=",", skip_header=1)
bristo

array([[ 12.1,  12. ],
       [ 11. ,  10.6],
       [ 14.1,  13.4],
       [ 13.8,  11.2],
       [ 15.5,  15.3],
       [ 12.2,  13.6],
       [ 12.8,  12.6],
       [  9.9,   8.8],
       [ 10.8,   9.6],
       [ 12.7,  12.4]])

In [5]:
bristo.shape

(10, 2)

In [6]:
np.mean(bristo[1])

10.800000000000001

In [7]:
bristo

array([[ 12.1,  12. ],
       [ 11. ,  10.6],
       [ 14.1,  13.4],
       [ 13.8,  11.2],
       [ 15.5,  15.3],
       [ 12.2,  13.6],
       [ 12.8,  12.6],
       [  9.9,   8.8],
       [ 10.8,   9.6],
       [ 12.7,  12.4]])

In [8]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
bristo

array([[ 12.1,  12. ],
       [ 11. ,  10.6],
       [ 14.1,  13.4],
       [ 13.8,  11.2],
       [ 15.5,  15.3],
       [ 12.2,  13.6],
       [ 12.8,  12.6],
       [  9.9,   8.8],
       [ 10.8,   9.6],
       [ 12.7,  12.4]])

In [10]:
transBristo =np.transpose(bristo)
transBristo

array([[ 12.1,  11. ,  14.1,  13.8,  15.5,  12.2,  12.8,   9.9,  10.8,
         12.7],
       [ 12. ,  10.6,  13.4,  11.2,  15.3,  13.6,  12.6,   8.8,   9.6,
         12.4]])

In [11]:
transBristo[:1,]

array([[ 12.1,  11. ,  14.1,  13.8,  15.5,  12.2,  12.8,   9.9,  10.8,
         12.7]])

In [12]:
np.mean(transBristo[:,1])

10.800000000000001

In [13]:
##Mean of the first column
np.mean(bristo[:,0])

12.49

In [17]:
##Mean of the second column
Before = bristo[:,0]
After = bristo[:,1]
difference = Before - After

In [16]:
np.mean(After)

11.949999999999999

In [21]:
difference

0.96353515763567288

In [22]:
np.mean(difference)

0.54000000000000004

In [23]:
np.std(difference)

0.96353515763567288